# You can use this file to create a conda environment for this pipeline:
name: nsclc-ici-biomarkers
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - r-base==4.1
  - r-tidyverse
  - r-devtools
  - r-dplyr
  - r-optparse
  - r-data.table
  - r-stringr
  - r-polychrome==1.5.1
  - bioconductor-genvisr>=1.20.0
  - matplotlib==3.5.2
  - numpy==1.22.4
  - pandas==1.4.2
  - libstdcxx-ng
  - chardet=5.2.0
  - pip
  - pip:
    - cycler==0.11.0
    - eli5==0.13.0
    - gitpython==3.1.27
    - python-dateutil==2.8.2
    - tensorflow==2.9.1
    - tensorflow-probability>=0.8.0
    - xgboost==1.6.1
    - seaborn==0.11.2
    - fuzzywuzzy==0.18.0
    - Levenshtein==0.23.0
    - python-Levenshtein==0.23.0 
    - rapidfuzz==3.5.2
    - nltk==3.8.1
    - scikit-learn==1.1.1
    - scipy==1.8.1
    - ruamel.yaml<=0.18.0
    - tqdm==4.46.0
    - llvmlite==0.41.1 
    - numba==0.58.1 
    - shap==0.44.1 
    - slicer==0.0.7
    - psutil==6.0.0  
    - comut==0.0.3
    - palettable==3.3.0
