# Preprocessing meta info
preprocessor_name: "non_null_one_hotted" #"main_preprocessor"
test_set_size: 0.2 # Part of data. 1 is all data.
random_seed: 42 # sets seed for training/test set splits
output_name: numerical_preprocess

# Data info
data_path: DataAssembly/Data
genetic_cols_rm: [] # specify more genetic variants to rm from study
general_cols_rm: [] #specify general cols to rm
studies_to_exclude: ["Jordan_2017"] # use cancer_study_identifier labels instead to match 
