# Training info
training_name: xgboost_model
random_seed: 42 # sets seed for model initiation

# Model info
model: xgboost
# Any specific args for the model
args: { 
  tree_method: hist,
  enable_categorical: true
}

# Data info
preprocessed_data_path: data/preprocessed/data_20220710-191043/data/train_data.csv
gt_column: "Treatment_Outcome"